### ISSUE TITLE
Add green-energy-hub to LF Energy landscape?

### ISSUE THREAD

**Issue by nicorikken** [Energinet-DataHub/green-energy-hub#182]
For the LFEnergy there is a [landscape page](https://landscape.lfenergy.org/) that maps software projects in an high-level architecture. More on this technical architecture is available on the [website](https://www.lfenergy.org/projects/functional-architecture/) or in this video recording of the [Technical Architecture Workshop in 2020](https://youtu.be/FLhWR_HefZo?t=190). Of course the LFEnergy are represented here, but also other software projects that exist in the same category, both open source or proprietary software.

Green Energy Hub is not on this landscape page, despite being targeted towards the energy sector and even being open source. It makes sense to add Green Energy Hub there. I'm happy to make a pull-request to the [landschape git repository](https://github.com/lf-energy/lfenergy-landscape) but decided to first come here to discuss it with you.

I was thinking of adding the following data to the [landscape.yml](https://github.com/lf-energy/lfenergy-landscape/blob/main/landscape.yml) file, under the section **Shared > Data Management**. I can also see this being categorized in the **Customer and Market** section, but that does not (yet) seem to have a data management category.

```yaml
          - item:
            name: Green Energy Hub
            description:  National energy transmission system operator data hub developing to support change toward decarbonised economies.
            homepage_url: https://github.com/Energinet-DataHub/green-energy-hub
            repo_url: https://github.com/Energinet-DataHub/green-energy-hub
            logo: # Do you have a SVG image?
            twitter: https://twitter.com/energinetdk
            crunchbase: https://www.crunchbase.com/organization/energinet-dk
```

- [ ] I would need to have an SVG image. I can only find the jpg from the git repo. I can try to remake it as a vector, but perhaps you already have an SVG available that can be submitted to the landscape page?

What do you think of this idea and details? Would you like to file the PR yourself, or should I do it?
